# -*- coding: utf-8 -*-

#Designed by Ao Wang, 15300240004

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QAction, QListWidgetItem
import sys
import os
from socket import *
import json
sys.path.append("IP.py")
import IP as ip

class Admininterface_Dialog(QDialog):
    this_hide = QtCore.pyqtSignal()
    act_fail = QtCore.pyqtSignal()
    shop_chose = QtCore.pyqtSignal(dict)
    new_user = QtCore.pyqtSignal()
    def __init__(self,parent=None):
        super(Admininterface_Dialog,self).__init__(parent)
        self.path=sys.path[0]
        os.chdir(self.path)#get the current directory
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(690, 510)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(30, 80, 140, 400))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CurrentAdminLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.CurrentAdminLine.setObjectName("CurrentAdminLine")
        self.CurrentAdminLine.setReadOnly(True)
        self.verticalLayout_6.addWidget(self.CurrentAdminLine)
        self.HeadImage = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.HeadImage.setObjectName("HeadImage")
        self.HeadImage.setFixedHeight(120)
        self.HeadImage.setFixedWidth(120)
        self.verticalLayout_6.addWidget(self.HeadImage)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        spacerItem94 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem94)
        self.AddNewUserButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.AddNewUserButton.setObjectName("AddNewUserButton")
        self.AddNewUserButton.setIcon(QtGui.QIcon('icon/get.ico'))
        self.AddNewUserButton.clicked.connect(self.create_new_user)
        self.horizontalLayout_44.addWidget(self.AddNewUserButton)
        spacerItem104 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem104)
        self.verticalLayout_6.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.ExitButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.ExitButton.setObjectName("ExitButton")
        self.ExitButton.setIcon(QtGui.QIcon('icon/redcross.ico'))
        self.ExitButton.clicked.connect(self.exit)
        self.horizontalLayout_14.addWidget(self.ExitButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(30, 20, 630, 30))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(200, 80, 460, 400))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_7)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 400, 330))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.UserMessageLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.UserMessageLine.setObjectName("UserMessageLine")
        self.horizontalLayout_3.addWidget(self.UserMessageLine)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.UserMessageOKButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.UserMessageOKButton.setObjectName("UserMessageOKButton")
        self.UserMessageOKButton.setIcon(QtGui.QIcon('icon/confirm.ico'))
        self.UserMessageOKButton.clicked.connect(self.send_or_broadcast_message)
        self.horizontalLayout.addWidget(self.UserMessageOKButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.UserMessageClearButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.UserMessageClearButton.setObjectName("UserMessageClearButton")
        self.UserMessageClearButton.setIcon(QtGui.QIcon('icon/empty.ico'))
        self.UserMessageClearButton.clicked.connect(self.message_clear)
        self.horizontalLayout.addWidget(self.UserMessageClearButton)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(50, 20, 360, 320))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ShopList = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.ShopList.setObjectName("ShopList")
        self.verticalLayout_3.addWidget(self.ShopList)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.ShowShopOKButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.ShowShopOKButton.setObjectName("ShowShopOKButton")
        self.ShowShopOKButton.setIcon(QtGui.QIcon('icon/confirm.ico'))
        self.ShowShopOKButton.clicked.connect(self.get_shop_info)
        self.horizontalLayout_9.addWidget(self.ShowShopOKButton)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.ShowShopClearButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.ShowShopClearButton.setObjectName("ShowShopClearButton")
        self.ShowShopClearButton.setIcon(QtGui.QIcon('icon/empty.ico'))
        self.ShowShopClearButton.clicked.connect(self.shop_clear)
        self.horizontalLayout_9.addWidget(self.ShowShopClearButton)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(50, 20, 360, 320))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.UserList = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        self.UserList.setObjectName("UserList")
        self.verticalLayout_4.addWidget(self.UserList)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.ShowUserOKButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.ShowUserOKButton.setObjectName("ShowUserOKButton")
        self.ShowUserOKButton.setIcon(QtGui.QIcon('icon/confirm.ico'))
        self.ShowUserOKButton.clicked.connect(self.get_all_user)
        self.horizontalLayout_10.addWidget(self.ShowUserOKButton)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.ShowUserClearButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.ShowUserClearButton.setObjectName("ShowUserClearButton")
        self.ShowUserClearButton.setIcon(QtGui.QIcon('icon/empty.ico'))
        self.ShowUserClearButton.clicked.connect(self.user_list_clear)
        self.horizontalLayout_10.addWidget(self.ShowUserClearButton)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_266 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_266.setGeometry(QtCore.QRect(40, 40, 380, 300))
        self.verticalLayoutWidget_266.setObjectName("verticalLayoutWidget_266")
        self.verticalLayout_266 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_266)
        self.verticalLayout_266.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_266.setObjectName("verticalLayout_266")
        spacerItem2066 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_266.addItem(spacerItem2066)
        self.horizontalLayout_866 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_866.setObjectName("horizontalLayout_866")
        self.label_466 = QtWidgets.QLabel(self.verticalLayoutWidget_266)
        self.label_466.setObjectName("label_466")
        self.horizontalLayout_866.addWidget(self.label_466)
        spacerItem2166 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_866.addItem(spacerItem2166)
        self.verticalLayout_266.addLayout(self.horizontalLayout_866)
        self.horizontalLayout_766 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_766.setObjectName("horizontalLayout_766")
        spacerItem2266 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_766.addItem(spacerItem2266)
        self.OpenShopUserLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_266)
        self.OpenShopUserLine.setObjectName("OpenShopUserLine")
        self.horizontalLayout_766.addWidget(self.OpenShopUserLine)
        spacerItem2366 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_766.addItem(spacerItem2366)
        self.verticalLayout_266.addLayout(self.horizontalLayout_766)
        self.horizontalLayout_2166 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2166.setObjectName("horizontalLayout_2166")
        self.label_866 = QtWidgets.QLabel(self.verticalLayoutWidget_266)
        self.label_866.setObjectName("label_866")
        self.horizontalLayout_2166.addWidget(self.label_866)
        spacerItem2466 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2166.addItem(spacerItem2466)
        self.verticalLayout_266.addLayout(self.horizontalLayout_2166)
        self.horizontalLayout_2266 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2266.setObjectName("horizontalLayout_2266")
        spacerItem2566 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2266.addItem(spacerItem2566)
        self.OpenShopShopNameLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_266)
        self.OpenShopShopNameLine.setObjectName("OpenShopShopNameLine")
        self.horizontalLayout_2266.addWidget(self.OpenShopShopNameLine)
        spacerItem2666 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2266.addItem(spacerItem2666)
        self.verticalLayout_266.addLayout(self.horizontalLayout_2266)
        self.horizontalLayout_666 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_666.setObjectName("horizontalLayout_666")
        spacerItem2766 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_666.addItem(spacerItem2766)
        self.OpenShopOKButton = QtWidgets.QPushButton(self.verticalLayoutWidget_266)
        self.OpenShopOKButton.setObjectName("OpenShopOKButton")
        self.OpenShopOKButton.setIcon(QtGui.QIcon('icon/confirm.ico'))
        self.OpenShopOKButton.clicked.connect(self.open_shop)
        self.horizontalLayout_666.addWidget(self.OpenShopOKButton)
        spacerItem2866 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_666.addItem(spacerItem2866)
        self.OpenShopClearButton = QtWidgets.QPushButton(self.verticalLayoutWidget_266)
        self.OpenShopClearButton.setObjectName("OpenShopClearButton")
        self.OpenShopClearButton.setIcon(QtGui.QIcon('icon/empty.ico'))
        self.OpenShopClearButton.clicked.connect(self.open_shop_clear)
        self.horizontalLayout_666.addWidget(self.OpenShopClearButton)
        spacerItem2966 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_666.addItem(spacerItem2966)
        self.verticalLayout_266.addLayout(self.horizontalLayout_666)
        spacerItem3066 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_266.addItem(spacerItem3066)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(40, 40, 380, 300))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem28)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem29)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem30)
        self.CloseShopUserLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.CloseShopUserLine.setObjectName("CloseShopUserLine")
        self.horizontalLayout_12.addWidget(self.CloseShopUserLine)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem31)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem32)
        self.CloseShopOKButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.CloseShopOKButton.setObjectName("CloseShopOKButton")
        self.CloseShopOKButton.setIcon(QtGui.QIcon('icon/confirm.ico'))
        self.CloseShopOKButton.clicked.connect(self.close_shop)
        self.horizontalLayout_13.addWidget(self.CloseShopOKButton)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem33)
        self.CloseShopClearButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.CloseShopClearButton.setObjectName("CloseShopClearButton")
        self.CloseShopClearButton.setIcon(QtGui.QIcon('icon/empty.ico'))
        self.CloseShopClearButton.clicked.connect(self.close_shop_clear)
        self.horizontalLayout_13.addWidget(self.CloseShopClearButton)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem34)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem35)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_6)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(50, 20, 360, 300))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_20.addWidget(self.label_6)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem36)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem37)
        self.RemainingUserLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.RemainingUserLine.setObjectName("RemainingUserLine")
        self.RemainingUserLine.textChanged.connect(self.remaining_num_clear)
        self.horizontalLayout_19.addWidget(self.RemainingUserLine)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem38)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_18.addWidget(self.label_7)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem39)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem40)
        self.RemainingNumLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.RemainingNumLine.setObjectName("RemainingNumLine")
        self.RemainingNumLine.setReadOnly(True)
        self.horizontalLayout_17.addWidget(self.RemainingNumLine)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem41)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem42)
        self.RemainingOKButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.RemainingOKButton.setObjectName("RemainingOKButton")
        self.RemainingOKButton.setIcon(QtGui.QIcon('icon/confirm.ico'))
        self.RemainingOKButton.clicked.connect(self.get_user_remaining)
        self.horizontalLayout_16.addWidget(self.RemainingOKButton)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem43)
        self.RemainingClearButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.RemainingClearButton.setObjectName("RemainingClearButton")
        self.RemainingClearButton.setIcon(QtGui.QIcon('icon/empty.ico'))
        self.RemainingClearButton.clicked.connect(self.remaining_clear)
        self.horizontalLayout_16.addWidget(self.RemainingClearButton)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem44)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_7.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.ShopList.itemClicked.connect(self.item_clicked)#!!!!!!!!!!

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Admin Interface"))
        self.HeadImage.setText(_translate("Dialog", ""))
        self.ExitButton.setText(_translate("Dialog", "Exit"))
        self.label.setText(_translate("Dialog", "Simple&Naive Mall Admin Interface"))
        self.label_2.setText(_translate("Dialog", "The User (Empty is to all users):"))
        self.label_3.setText(_translate("Dialog", "Content:"))
        self.UserMessageOKButton.setText(_translate("Dialog", "OK"))
        self.UserMessageClearButton.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Messages"))
        self.ShowShopOKButton.setText(_translate("Dialog", "OK"))
        self.ShowShopClearButton.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", " Shops "))
        self.ShowUserOKButton.setText(_translate("Dialog", "OK"))
        self.ShowUserClearButton.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", " Users "))
        self.label_466.setText(_translate("Dialog", "User ID:"))
        self.label_866.setText(_translate("Dialog", "Shop Name:"))
        self.OpenShopOKButton.setText(_translate("Dialog", "OK"))
        self.OpenShopClearButton.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Open Shops"))
        self.label_5.setText(_translate("Dialog", "User ID:"))
        self.CloseShopOKButton.setText(_translate("Dialog", "OK"))
        self.CloseShopClearButton.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Close Shops"))
        self.label_6.setText(_translate("Dialog", "Input the user ID you want to query:"))
        self.label_7.setText(_translate("Dialog", "Remaining:"))
        self.RemainingOKButton.setText(_translate("Dialog", "OK"))
        self.RemainingClearButton.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Remaining"))
        self.AddNewUserButton.setText(_translate("Dialog", "New User"))

        file = QtCore.QFile('black_flat.qss')
        file.open(QtCore.QFile.ReadOnly)
        styleSheet = file.readAll()
        styleSheet = unicode(styleSheet, encoding='utf8')
        self.setStyleSheet(styleSheet)
        file.close()

    def clear_everything(self):
        self.CloseShopUserLine.clear()
        self.CurrentAdminLine.clear()
        self.OpenShopUserLine.clear()
        self.OpenShopShopNameLine.clear()
        self.UserMessageLine.clear()
        self.ShopList.clear()
        self.UserList.clear()
        self.textEdit.clear()
        self.RemainingNumLine.clear()
        self.RemainingUserLine.clear()
        self.HeadImage.clear()
    
    def receive_admin_argument(self,dic):    #接收管理员信息
        self.clear_everything()
        self.show()
        self.id=dic["id"]
        self.name=dic["name"]
        self.CurrentAdminLine.setText(str("Admin: " + self.name))

        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        info["request"]="headimage"
        info["id"]=self.id
        info["authority"]="admin"
        info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)

        with open('tmp/image.jpg', 'ab') as f:  #显示接收的管理员头像
            f.write(data)
        
        pixmap=QtGui.QPixmap("tmp/image.jpg").scaled(120, 120, transformMode=QtCore.Qt.SmoothTransformation)
        self.HeadImage.setPixmap(pixmap)

        os.remove(str("tmp/image.jpg"))#attention
        s.close()
    
    def exit(self):
        self.hide()
        self.clear_everything()
        self.this_hide.emit()
    
    def send_or_broadcast_message(self):
        user_id=self.UserMessageLine.text()
        text=self.textEdit.toPlainText()
        self.textEdit.clear()
        
        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        if user_id == "":   #为空，要广播
            info["request"]="broadcast"
            info["content"]=text
            info["timestamp"]=ip.get_time_stamp()
        else:
            info["request"]="inform"
            info["user_id"]=user_id
            info["content"]=text
            info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)
        data=eval(data)
        if data["state"]=="fail":
            self.act_fail.emit()
        elif data["state"]=="succeed":
            self.UserMessageLine.clear()
        s.close()
    
    def message_clear(self):
        self.UserMessageLine.clear()
        self.textEdit.clear()
    
    def get_shop_info(self):    #接收商店信息
        self.ShopList.clear()
        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        info["request"]="shopinfo"
        info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)
        shop_dic=eval(data)

        self.shop_id=[]
        shop_num=len(shop_dic)
        for i in range(shop_num):
            string="Shop Name: "+shop_dic[str(i)]["shopname"]+"\n"+"Owner ID: "+shop_dic[str(i)]["id"]+"\n"+"Owner name: "+shop_dic[str(i)]["ownername"]+'\n'
            item=QListWidgetItem()
            item.setIcon(QtGui.QIcon('icon/shop.ico'))
            item.setText(string)
            self.shop_id.append(int(shop_dic[str(i)]["id"]))
            self.ShopList.insertItem(i,item)
        s.close()
    
    def shop_clear(self):
        self.ShopList.clear()
    
    def get_all_user(self): #获取所有顾客信息
        self.UserList.clear()
        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        info["request"]="get_all_user"
        info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)
        lis=eval(data)
        i=0
        for thing in lis:
            string="User ID: "+thing["user_id"]+"\n"+"User name: "+thing["user_name"]+"\n"
            item=QListWidgetItem()
            item.setIcon(QtGui.QIcon('icon/list.ico'))
            item.setText(string)
            self.UserList.insertItem(i,item)
            i+=1
        s.close()
    
    def user_list_clear(self):
        self.UserList.clear()
    
    def open_shop(self):    #开店
        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        info["request"]="open_shop"
        info["user_id"]=self.OpenShopUserLine.text()
        info["shop_name"]=self.OpenShopShopNameLine.text()
        info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)
        data=eval(data)
        if data["state"]=="fail":
            self.act_fail.emit()
            self.open_shop_clear()
        elif data["state"]=="succeed":
            self.open_shop_clear()
        s.close()
    
    def open_shop_clear(self):
        self.OpenShopShopNameLine.clear()
        self.OpenShopUserLine.clear()
    
    def close_shop(self):   #关闭商店
        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        info["request"]="get_customer_in_shop"
        info["shop_id"]=self.CloseShopUserLine.text()
        info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)
        cus_list=eval(data)
        s.close()
        
        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        info["request"]="close_shop"
        info["user_id"]=self.CloseShopUserLine.text()
        info["customer"]=cus_list
        info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)
        data=eval(data)
        if data["state"]=="fail":
            self.act_fail.emit()
        s.close()
        self.CloseShopUserLine.clear()
    
    def close_shop_clear(self):
        self.CloseShopUserLine.clear()
    
    def get_user_remaining(self):   #获取用户余额
        s=socket(AF_INET,SOCK_DGRAM)
        timeout = ip.TIMEOUT
        s.settimeout(timeout)
        info={}
        info["request"]="get_user_remaining"
        info["user_id"]=self.RemainingUserLine.text()
        info["timestamp"]=ip.get_time_stamp()
        info = json.dumps(info)
        res=ip.encrypt(info)#encrypt
        s.sendto(res,(ip.HOST,ip.PORT))
        data,ADDR = s.recvfrom(ip.BUFFERSIZE)
        data=ip.decrypt(data)
        data=eval(data)
        if data["state"]=="fail":
            self.act_fail.emit()
            self.RemainingUserLine.clear()
            self.RemainingNumLine.clear()
        elif data["state"]=="succeed":
            string="$"+str(data["remaining"])
            self.RemainingNumLine.setText(string)
        s.close()
        return
    
    def remaining_clear(self):
        self.RemainingUserLine.clear()
        self.RemainingNumLine.clear()
    
    def remaining_num_clear(self):
        self.RemainingNumLine.clear()
    
    def item_clicked(self,item):    #点击商店后，发送信息，进入商店
        dic={}
        dic["shop_id"]=self.shop_id[self.ShopList.currentRow()]
        dic["admin_id"]=self.id
        dic["admin_name"]=self.name
        self.shop_chose.emit(dic)
        self.hide
    
    def create_new_user(self):
        self.new_user.emit()


if __name__ == "__main__":
    app = QApplication(sys.argv)    
    window = Admininterface_Dialog()
    window.show()
    sys.exit(app.exec_()) 